name: login_demo_flutter
description: Login Demo Project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Network
  http: ^0.13.4
  # Notify Helper
  fluttertoast: ^8.0.9
  # State Helper
  provider: ^6.0.2
  # Json Helper
  json_annotation: ^4.4.0
  # General Helpers
  form_field_validator: ^1.1.0
  date_field: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  # Generator Starter
  build_runner: ^2.1.8
  # Json Generator
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true

 # Assets
  assets:
    - assets/images/
